# Generated by Django 4.2.3 on 2023-08-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('mobiles', 'Mobiles'), ('cameras', 'Cameras'), ('home_appliances', 'Home Appliances'), ('tablets', 'Tablets'), ('gaming', 'Gaming'), ('smart_watches', 'Smart Watches')], max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_id',
            field=models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False),
        ),
    ]
