# Generated by Django 4.2.3 on 2023-08-11 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyers',
            old_name='conatact_no',
            new_name='contact_no',
        ),
    ]
