# Generated by Django 4.2.3 on 2023-08-17 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customlogentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
