# Generated by Django 4.2.3 on 2023-08-17 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomLogEntry',
        ),
    ]
