# Generated by Django 4.2.3 on 2023-08-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_contact_no_buyers_conatact_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyers',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='buyers',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='buyers',
            name='contact_no',
            field=models.CharField(default=123456789, max_length=10),
            preserve_default=False,
        ),
    ]
