# Generated by Django 4.2.3 on 2023-08-18 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_cusstomuser_address_cusstomuser_contact_no_and_more'),
        ('order', '0002_orders_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='buyer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customuser.cusstomuser'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
