# Generated by Django 4.2.3 on 2023-08-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orders_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='buyer_id',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
