# Generated by Django 4.2.3 on 2023-08-17 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cusstomuser',
            name='address',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cusstomuser',
            name='contact_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cusstomuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cusstomuser',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
